### ISSUE TITLE
Task List to check before submission (from assign info)

### ISSUE THREAD

**Issue by lemireg** [warlicks/dungon-adventrue#11]
**TO BUILD**
- [x] Room contains (items/behaviors):
    - [x] Healing potion (heals 5-15 hit points, randomly generated)
    - [x] Pit (damages 1-20 hit points, randomly generated)
    - [x] Entrance (only one room has an entrance and the room with the entrance contains nothing else)
    - [x] Exit (only one room contains exit and the room that contains the exit contains nothing else) 
    - [x] Doors (N, S, E, W)
    - [x] 10% probability (modifiable constant) a room will contains a healing potion, vision potion and pit (each of these are independent of the other)
    - [x] Vision potion (can be used to allow user to see eight rooms surrounding current room and current room. location in maze may cause less than 8 to be displayed)
    - [x] contain _ _ str _ _() method to build 2D graphical rep of room (may use any graphical components you wish). The (command line) representation is as follows: 
```
        * - * will represent a north/south door (the - represents the door). If the room is on a boundary of the maze (upper or lower), then that will be represented with ***
        East/west doors will be represented in a similar fashion with the door being the | character as opposed to a -.
        In the center of the room you will display a letter that represents what the room contains. Here are the letters to use and what they represent:
            M - Multiple Items
            X - Pit
            i - Entrance (In)
            O - Exit (Out)
            V - Vision Potion
            H - Healing Potion
            <space> - Empty Room
            A, E, I, P - Pillars

Example:

Room 1,1 might look like
*-*
|P |
*-*

Room 0,0 might look like
***
*E|
*-*
```

- [x] Adventurer
    - [x] Has a name
    - [x] contains:
        - [x] hit points (initially 75-100, randomly generated)
        - [x] number of healing potions
        - [x] number of vision potions
        - [x] which pillars found
    - [x] ability to move in dungeon (might decide to place this behavior elsewhere)
    - [x] increases or decreases the hit points accordingly
    - [x] _ _ str _ _() method that build a string containing: name, hit points, total healing potions, total vision potions, list of pillar pieces found 

- [x] Adventurer and Room need to be able to interact (Adventurer automatically picks up potion if in a room with it, or auto falls in a pit if in the room. Potion total in room will be changed after).

- [x] Dungeon
    - [x] creates/contains a maze of rooms (maze is randomly generated, data structure for maze is up to us: list of lists, linked list of linked lists, )
    - [x] algorithm should ensure travel from entrance to exit is possible once maze is generated
    - [x] maze should have "dead ends"
    - [x] places the entrance, exit, and the pillars. no two pillars can be in the same room, pillars cannot be in entrance or exit
    - [ ] (possibly) maintains location of the adventurer in the dungeon
    - [x] contains _ _ str _ _() method that builds a string containing info about the entire dungeon

 - [x] Dungeon Adventure
     - [x] contains main logic for playing the game
     - [x] introduces the game describing what the game is about and how to play
     - [x] creates a dungeon object and adventurer object
     - [x] obtains the name of the adventurer from the user
     - [x] does the following repetitively
         - [x] prints current room 
         - [x] determines adventurers options (use, use a potion)
         - [x] continues this process until the adventurer wins or dies
     - [x] Include a hidden menu option for testing that prints out the entire dungeon (specify what menu optio is in your documentation for the DungeonAdventure class)
     - [x] At the conclusion of the game display the entire dungeon

- [ ] Can get bonus marks for creativity etc - make sure to outline in readme
    - [ ] idea that could A) make it easier to make winning and losing games and B) be "low hanging fruit" (maybe easy to implement) is to use different distributions to generate the values for potions and pits for different "levels" of difficulty of game (maybe a harder way to change difficulty is how many dead-ends there are or how long the maze is).

**TO TURN IN**
- [ ] zip file with team member last names
- [x] python source files (pycharm project folder is fine too)
- [x] UML class diagram that represents the classes in solution (and their relations to one another)
- [x] screenshots (or tests) that show
    - [x] maze generation works
    - [x] example of losing game  (if in "tests" can set a seed to recreate)  
    - [x] example of winning game   (if in "tests" can set a seed to recreate)
    - [x] for these tests can (should) make maze smaller to test things more easily
- [x] readme with - what work each person did, estimate of time spent on project, shortcomings of project, any other useful info for grading
- [x] Note to self: go through rubric at end to check everything is in it

**Comment by lemireg** [comment]
I'm going through code right now and I'll make some notes here.

would it be easier to combine `def increase_health(self, amount: int) -> None:` and `def decrease_health(self, amount: int) -> None:` (in the adventurer class)... to see how it's implemented before making any changes

**Comment by warlicks** [comment]
@lemireg I'm looking for low hanging fruit tonight and going to work on implementing `__str__` in the `Room` class.

**Comment by warlicks** [comment]
Notes as I tick off boxes.
"ability to move in dungeon (might decide to place this behavior elsewhere)"
* Managed by as a part of the game logic in `DungeonAdventure`. 

"Adventurer and Room need to be able to interact (Adventurer automatically picks up potion if in a room with it, or auto falls in a pit if in the room. Potion total in room will be changed after)." 
* This is managed by methods in the `DungeonAdventure` beceause it made sense to include it in the game logic.

**Comment by lemireg** [comment]
working on:
`Vision potion (can be used to allow user to see eight rooms surrounding current room and current room. location in maze may cause less than 8 to be displayed)`

**Comment by warlicks** [comment]
I'm working on:
** Include a hidden menu option for testing that prints out the entire dungeon (specify what menu optio is in your documentation for the DungeonAdventure class)**

**Comment by lemireg** [comment]
@warlicks 

code for the outline of the logic

```
        elif action == 2:
            """Implement Health Potion. They can increase their health if they have
            Health Potion in their inventory."""
            if len(d.adventurer.inventory.get("health potion")) != 0:
                print("HEALTH POTION NOT IMPLEMENTED")
                d.adventurer.inventory["health potion"].pop(0)
            else:
                print("Nice try! You can't use a Health Potion unless it is in your inventory!\n")
```

**Comment by lemireg** [comment]
@warlicks 
https://us04web.zoom.us/j/73258659029?pwd=4VvaOjiPrYnDFHoipB44iVqTRNzPIk.1
